// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfhGPiAdbhA-Uynv6bQOWthfEXEJVoT38',
    appId: '1:152644406232:web:be9583da14aa33fcc2c0ad',
    messagingSenderId: '152644406232',
    projectId: 'farm-to-factory-8bd4d',
    authDomain: 'farm-to-factory-8bd4d.firebaseapp.com',
    storageBucket: 'farm-to-factory-8bd4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwxAG5WJrizGCPgLE-3g4v2G7WJn2b0aY',
    appId: '1:152644406232:android:fd61c373efe11d4dc2c0ad',
    messagingSenderId: '152644406232',
    projectId: 'farm-to-factory-8bd4d',
    storageBucket: 'farm-to-factory-8bd4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-a3qelMRiBMX5LyZsE_9lg8Ii_osW37g',
    appId: '1:152644406232:ios:d13a1f7f647ea134c2c0ad',
    messagingSenderId: '152644406232',
    projectId: 'farm-to-factory-8bd4d',
    storageBucket: 'farm-to-factory-8bd4d.firebasestorage.app',
    iosBundleId: 'com.example.farmToFactory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-a3qelMRiBMX5LyZsE_9lg8Ii_osW37g',
    appId: '1:152644406232:ios:d13a1f7f647ea134c2c0ad',
    messagingSenderId: '152644406232',
    projectId: 'farm-to-factory-8bd4d',
    storageBucket: 'farm-to-factory-8bd4d.firebasestorage.app',
    iosBundleId: 'com.example.farmToFactory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfhGPiAdbhA-Uynv6bQOWthfEXEJVoT38',
    appId: '1:152644406232:web:af2ebeab898bfc44c2c0ad',
    messagingSenderId: '152644406232',
    projectId: 'farm-to-factory-8bd4d',
    authDomain: 'farm-to-factory-8bd4d.firebaseapp.com',
    storageBucket: 'farm-to-factory-8bd4d.firebasestorage.app',
  );
}
